[package]
name = "mmproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
argwerk = "0.20.1"
cidr = "0.2.1"

[dependencies.tokio]
version = "1.23.0"
features = ["net", "rt-multi-thread", "macros"]
